# Sequencing data

## Sequencing depth

```{r sequencing_depth_overview, warning=FALSE, comments="", message=FALSE}

tibble(metric=c("Total GB", "Total reads", "Average GB", "Average reads"),
       value=unlist(c(round(all_data %>% summarise(sum(bases_pre_fastp)) / 1000000000,2),
               round(all_data %>% summarise(sum(bases_pre_fastp)) / 300,2),
               paste0(round(all_data %>% summarise(mean(bases_pre_fastp)) / 1000000000,2),"±",round(all_data %>% summarise(sd(bases_pre_fastp)) / 1000000000,2)),
               paste0(round(all_data %>% summarise(mean(bases_pre_fastp)) / 300,0),"±",round(all_data %>% summarise(sd(bases_pre_fastp)) / 300,0))))
       ) %>%
  tt()

```

```{r sequencing_depth_summary, warning=FALSE, comments="", message=FALSE}
all_data %>%
    group_by(Taxon,Extraction) %>%
    summarise(value = sprintf("%.1f±%.1f", mean(bases_post_fastp / 1000000000), sd(bases_post_fastp / 1000000000))) %>%
    pivot_wider(names_from = Extraction, values_from = value) %>%
    tt(caption = "Mean and standard deviation of sequencing depth (GB)")
```

```{r sequencing_depth_plot, warning=FALSE, comments="", message=FALSE, fig.height=4, fig.width=10, fig.fullwidth=TRUE}
all_data %>%
    select(Library,Species,Extraction,bases_pre_fastp,Taxon) %>%
    mutate(bases_pre_fastp=bases_pre_fastp/1000000000) %>%
    unique() %>%
    ggplot(aes(x=Extraction,y=bases_pre_fastp, color=Species, group=Extraction)) + 
        geom_boxplot(outlier.shape = NA, fill="#f4f4f4", color="#8c8c8c") + 
        geom_jitter() + 
        scale_color_manual(values=vertebrate_colors) +
        facet_grid(. ~ Taxon, scales = "free") +
        theme_minimal() +
        labs(y="Sequencing depth (Gb)",x="Extraction method")
```

```{r sequencing_depth_test, warning=FALSE, comments="", message=FALSE}
all_data  %>%
    filter(Taxon != "Control") %>%
    lmerTest::lmer(bases_post_fastp ~ Taxon + Extraction + (1 | Species/Sample), data = ., REML = TRUE) %>%
    plot()

all_data  %>%
    filter(Taxon != "Control") %>%
    lmerTest::lmer(bases_post_fastp ~ Taxon + Extraction + (1 | Species/Sample), data = ., REML = TRUE) %>%
    anova()

all_data  %>%
    filter(Taxon != "Control") %>%
    lmerTest::lmer(bases_post_fastp ~ Taxon + Extraction + (1 | Species/Sample), data = ., REML = TRUE) %>%
    broom.mixed::tidy() %>%
    tt()

all_data  %>%
    filter(Taxon != "Control") %>%
    lmerTest::lmer(bases_post_fastp ~ Taxon + Extraction + (1 | Species/Sample), data = ., REML = TRUE) %>%
    plot_model(.,type="pred",terms=c("Taxon","Extraction"))

all_data  %>%
    filter(Taxon != "Control") %>%
    lmerTest::lmer(bases_post_fastp ~ Taxon + Extraction + (1 | Species/Sample), data = ., REML = TRUE) %>%
    plot_model(.,type="pred",terms=c("Species"),pred.type = "re",ci.lvl = NA)+
        theme(axis.text.x = element_text(angle = 45, hjust = 1))

all_data  %>%
    filter(Taxon != "Control") %>%
    lmerTest::lmer(bases_post_fastp ~ Taxon + Extraction + (1 | Species/Sample), data = ., REML = TRUE) %>%
    r.squaredGLMM()
```
## Quality-filtering

```{r qc_summary, warning=FALSE, comments="", message=FALSE}
all_data %>%
    mutate(qf_bases=bases_post_fastp/bases_pre_fastp*100) %>%
    group_by(Taxon,Extraction) %>%
    summarise(value = sprintf("%.1f±%.1f", mean(qf_bases), sd(qf_bases))) %>%
    pivot_wider(names_from = Extraction, values_from = value) %>%
    tt(caption = "Mean and standard deviation of quality-filtered proportion of reads")
```

```{r qc_plot, warning=FALSE, comments="", message=FALSE, fig.height=4, fig.width=10, fig.fullwidth=TRUE}
all_data %>%
    mutate(qf_bases=bases_post_fastp/bases_pre_fastp*100) %>%
    select(Library,Species,Extraction,qf_bases,Taxon) %>%
    unique() %>%
    ggplot(aes(x=Extraction,y=qf_bases, color=Species, group=Extraction)) + 
        geom_boxplot(outlier.shape = NA, fill="#f4f4f4", color="#8c8c8c") + 
        geom_jitter() + 
        scale_color_manual(values=vertebrate_colors) +
        facet_grid(. ~ Taxon, scales = "free") +
        theme_minimal() +
        labs(y="High-quality data (%)",x="Extraction method")
```

```{r qc_test, warning=FALSE, comments="", message=FALSE}
data<-all_data  %>%
    mutate(qf_bases=bases_post_fastp/bases_pre_fastp,unique_sample=factor(1:nrow(all_data))) %>%
    filter(Taxon != "Control") 

M <-MASS::glmmPQL(qf_bases~ Taxon+Extraction,random=~1|Species/Sample,
               family="quasibinomial",data=data)

Anova_table<-car::Anova(M,test.statistic="Wald",type="III")%>%
    mutate(F=Chisq/Df) # Approximate F value
n <- nrow(M$data)  # Total number of observations
df_fixed <- length(fixef(M))  # Number of fixed effect parameters
df_random <- length(ranef(M))  # Number of random effect parameters (or levels)
approx_residual_df <- n - df_fixed - df_random # Approx. residual Df
data.frame(Anova_table,
           p_value=pf(Anova_table$F, Anova_table$Df, approx_residual_df, lower.tail = FALSE))%>%
  select(F,p_value)

broom.mixed::tidy(M) %>%
    tt()

plot_model(M,type="pred",terms=c("Taxon","Extraction"))
```