# (PART) PROTOCOLS {-}
# Sample homogeneisation and digestion {#sample-digestion}
Homogenisation and digestion of biological samples like faeces or intestinal contents are crucial steps in the process of DNA extraction. These steps help break down the complex matrix of the sample, thus separating different compounds and molecules from each other. Faeces, for example, are composed of a heterogeneous mixture of materials, including undigested food, microbial cells, host cells, and waste products. This complex matrix can make it challenging to access and extract DNA. Homogenisation involves breaking down the solid and semi-solid components of the sample, creating a more uniform mixture that is easier to work with, while digestion also entails degrading cellular structures to release intracellular compounds to the matrix.

The EHI samples are stored in a buffer that serves a dual purpose as both a preservative and a digestion buffer. The buffer facilitates the release of nucleic acids from cells and tissues through breaking down cellular membranes and structures.

The EHI protocol also includes bead-beating using a combination of ceramic, silica and glass beads for sample homogenisation. The mechanical force generated by the beads' movement and collision with the sample causes physical disruption, breaking apart cells and releasing their contents into the surrounding solution. Optimisation of bead-beating conditions is necessary to balance efficient disruption with minimal degradation, as depending on the sample, bead types, and shearing time, there is a potential risk of shearing or damaging sensitive biomolecules.

## Instruments, plasticware and reagents
### Instruments {-}
- Bead mill/beater homogenizer e.g. TissueLyser II (Qiagen)
- Analytical balance (for tissue sample)
- Block Heater-Shaker e.g. ThermoMixer C (Eppendorf) (for tissue sample)
- SAFE® Screw Cap De-/Capper (LVL technologies)
- SAFE® 2D/1D Code Reader (LVL technologies)

### Plasticware {-}
| Item      | Brand | Catalogue number        |
| :---        |    :----:   |          ---: |
| Lysing Matrix E 96-Well Plate | MP Biomedicals  | [116984001-CF](https://www.mpbio.com/us/116984001-lysing-matrix-e-96-well-1rack-cf)  |
| Polystyrene Tweezer (Single packed disposable sterile)  | Megro  |    |
| Carbon steel surgical scalpel blades (Single packed sterile)  |    | [1C-X10-BL-CW-B-S](https://www.lvl-technologies.com/en/sample-storage/safe-2d-tubes-engl/safe-96-xt-2D#lx-1000-96)  |
| LX 1000 - 2D Biobanking Tubes | LVL technologies | [1C-X10-BL-CW-B-S](1C-X10-BL-CW-B-S	https://www.lvl-technologies.com/en/sample-storage/safe-2d-tubes-engl/safe-96-xt-2D#lx-1000-96) |

### Reagents {-}
| Reagent      | Brand | Catalogue number        | Storage       |
| UltraPure™ 1M Tris Hydrochloride, Tris-HCI | Invitrogen | [15568025](https://www.thermofisher.com/order/catalog/product/15568025) |    4 ºC   |
| UltraPure™ 0.5M Ethylenediaminetetraacetic acid, EDTA | Invitrogen | [15575-038](https://www.thermofisher.com/order/catalog/product/15575020) |   25 ºC  |
| BioUltra Sodium dodecyl sulfate solution, SDS | Sigma Aldrich | [71736](https://www.sigmaaldrich.com/DK/en/product/sigma/71736) |   25 ºC  |
| Proteinase K  20 mg/ml  | Roche   |  [3115828001](https://www.sigmaaldrich.com/DK/en/product/roche/rprotksolro?gclid=Cj0KCQiAo7KqBhDhARIsAKhZ4uixPpwjNmozI9PHQqpP9lhoww18rXoEXY2W7iJeBGXqAj4uBHe5mHsaAo3qEALw_wcB)  |   4 ºC   |

## Protocol
### Faeces and swabs {-}
1. Thaw the samples and ensure samples have entirely thawed.
2. Spin down or gently centrifuge tubes briefly to remove any liquid from the lid.
3. Add the content of 1 well of the Lysing Matrix E 96-Well Plate to each collection tube.
4. Vortex to ensure that the beads are moving in each sample. If beads are not moving despite vortexing, it is an indication of overstuffing the sample. Consider using a sterile pipet tip to attempt unclogging the beads.
5. Homogenise the sample with the TissueLyser for two rounds of 6 minutes at max speed (=30 Hz).
6. Spin down or centrifuge the tubes at 2,2 g/rcf for 1 minute. Ensure no foam is present on the tube's lids. Otherwise, repeat centrifugation.
7. Gently transfer the supernatant to an LX 1000 LVL tube without disturbing the pellet+beads.

### Tissue samples {-}
1. Extract the tissue from the original preservation tube, dry it out and weight it on a sterile weighing boat.
2. If the tissue sample is heavier than 10 mg, cut a portion using a sterile scalpel and place it in an Eppendorf tube
3. Add 250 μl of SDS lysis buffer solution to the tube and 25 μl of proteinase K.
4. Incubation overnight at 56°C on a a thermoshaker.
5. Centrifuge/Spin Down** the tubes at 2,2 g/rcf for 1 minutes. Ensure no foam is present on the tube's lids. Otherwise, repeat centrifugation.
6. Transfer the digested sample to an LX 1000 LVL tube.
